### ISSUE TITLE
better color contrast for disabled menu options

### ISSUE THREAD

**Issue by qrockz** [AnonymouX47/termvisage#17]
![termv_greyedOut](https://github.com/AnonymouX47/termvisage/assets/56853194/8b1a04f9-faa7-43d6-a9ad-7f1f9fc5a5ca)

I have big trouble to see the disabled parts because of the current coloring (grey text + blue bg).

Maybe change it to something with better contrast.

**Comment by AnonymouX47** [comment]
Hmm :thinking:... Nice catch. I'll fix that soon.

I would ask why you'd want to see disabled actions :thinking:. Though, that's no excuse for the bad contrast. :laughing:

*Side note: Theming/Color customization is planned but that's maybe a little further way :smile:.*

Thanks :+1:.

**Comment by qrockz** [comment]
> I would ask why you'd want to see disabled actions 🤔. 

It gives me a hint about available functionality of your software.

**Comment by AnonymouX47** [comment]
Hello!

So sorry for the delay. I've actually made the changes since over a week now but due to an illness (I'm almost fully recovered now though :hugs:), I'm just pushing the changes.

So, how's this?

![Screenshot_2024-05-16_21-25-07](https://github.com/AnonymouX47/termvisage/assets/61663146/d215a77d-80f3-4475-990e-b8097aef7a08)

You can also install from the `key-bar` branch via:
```
# `pip` also works.
pipx install git+https://github.com/AnonymouX47/termvisage.git@key-bar
```
if you wish to verify how it looks on your end.

Thank you. :smiley:

**Comment by AnonymouX47** [comment]
@qrockz

Better still, how's this? (made some further changes :smiley:, see #19 for details)

![Screenshot_2024-05-19_21-36-41](https://github.com/AnonymouX47/termvisage/assets/61663146/de9910c0-9aff-43d9-8285-bcc3388b8bd3)

**Comment by qrockz** [comment]
Contrast is definitely better but it's also hard to read when those Navigation hints are all written next to each other. It would be nicer to display them in a table format thus it appears more organized and easier to read. 

![termv1](https://github.com/AnonymouX47/termvisage/assets/56853194/2f33665c-5997-49d3-a88f-cc5ab3d084f9)
![termv2](https://github.com/AnonymouX47/termvisage/assets/56853194/0a048945-e3c7-4938-89ab-ed963fbce383)

**Comment by AnonymouX47** [comment]
Oh, the functionality does exist already (_take note of the "**`F1` Help**" action listed in the footer in my screenshots above_). Perhaps, more elaborate than you've pictured above:

| ![Screenshot_2024-05-21_10-22-42](https://github.com/AnonymouX47/termvisage/assets/61663146/6dd86c0e-37a1-4fce-ad8e-a4f48a0e18cd) | ![Screenshot_2024-05-21_10-22-59](https://github.com/AnonymouX47/termvisage/assets/61663146/60c7acc6-48ab-4b39-a48e-b0910fa3aae6) |
|:---:|:---:|

I understand that this "**`F1` Help**" action might be occluded by default on terminal windows with a small width but:

1. The footer can always be expanded to show all actions available.
2. There are many apps that don't display a "Press <key> for Help" message, take `less` and `top` as examples.
3. I believe `F1` is a pretty common key to display help info. :thinking:
4. This functionality is documented in the [TUI Usage](https://github.com/AnonymouX47/termvisage#tui-terminal-user-interface) section of the README.

   Interestingly, I just noticed this isn't even mentioned throughout the docs :smiling_face_with_tear:... Gotta fix that!

That said, what's your opinion about the help screen?
Also which do you think is best as a default key for the "Help" action and why: `F1`, or `?` or `h`?

For what it's worth, I'm looking into implementing support for multiple keys per action. Would be really handy for some actions. :thinking:

**Comment by qrockz** [comment]
> That said, what's your opinion about the help screen?
Looks awesome!!

> Also, which do you think is best as a default key for the "Help" action and why: F1, or ? or h?
I'can't answer this question. Use all 3 of them :)

**Comment by AnonymouX47** [comment]
> Looks awesome!!

Glad to hear that. :smiley:

> I'can't answer this question. Use all 3 of them :)

:laughing:... That also works.

I'll implement support for multiple keys per action towards the release after the next ([v0.3.0](https://github.com/AnonymouX47/termvisage/milestone/4)).

> It's nice to have the action bar available but it would be nicer if the user also have the option to hide it.
> Experienced users don't need the action bar.
> What do you think :question: 

Hmm :thinking:... very true. Never even occurred to me. :facepalm:

I'll add a `show footer` config option and then I guess I'll go ahead to merge the PR.

Thank you very much. :pray:

**Comment by AnonymouX47** [comment]
Hurray! :partying_face:
It's all done now, I believe... On to the next one. :smiley:

Thanks so much for all your suggestions and feedback. :pray:

**Comment by AnonymouX47** [comment]
Hello again!

This is to inform you that [v0.2.0](https://github.com/AnonymouX47/termvisage/releases/tag/v0.2.0) has just been released, containing the fix/enhancement discussed in this issue. :tada:

You can upgrade to the new version by running:

```shell
pipx upgrade termvisage
# OR `pip install --upgrade termvisage`, if that's your installation method.
```
but if you've earlier installed the package from the git repository (remote or local) or some other source, you might need to run:

```shell
# The same also applies to `pip`
pipx install --force termvisage
```

Thanks so much for your report/suggestion, patience and feedback. :handshake: :smiley:
