### ISSUE TITLE
term-image to respect XDG Base Directories Specification

### ISSUE THREAD

**Issue by cmcallister** [AnonymouX47/termvisage#2]
**Is your feature request related to a problem? Please describe.**
Currently `term-image` stores and writes configuration files to $HOME/.term_image/

**Describe the solution you'd like**
If the system has `XDG_CONFIG_HOME` set,  please place configurations there (there may be other considerations, see [XDG Base Directories Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html))

**Describe alternatives you've considered**
Thought about a symlink, but that still leaves another line of output when listing the home directory

**Comment by AnonymouX47** [comment]
Finally putting this to rest. :smiley:

I've updated every aspect of the tool that used `~/.term_image` to now use XDG Base Directories (or system/user-specific directories in the case of temporary files).

I'm sorry it took so long.
