### ISSUE TITLE
Pixelated image instead of high resolution im age displayed by default settings

### ISSUE THREAD

**Issue by kianmeng** [AnonymouX47/termvisage#7]
**Description**
Cannot display high resolution image.

**To Reproduce**

1. `pipx install termvisage`
2. `wget https://user-images.githubusercontent.com/61663146/235449392-b464ff19-82ac-4c55-9244-e718bc999e98.png`
3. `termvisage 235449392-b464ff19-82ac-4c55-9244-e718bc999e98.png`

**Expected behavior**
Expect to see a high resolution image instead of pixelated image.

**Screenshots**
![Screenshot from 2023-07-21 07-24-51](https://github.com/AnonymouX47/termvisage/assets/134518/485824e8-a8b3-4489-85b8-c7f56c56994f)

**Desktop (please complete the following information, if applicable):**

- OS: Ubuntu
- Version: 23.04
- Kernel version (if applicable): 6.2.0

**Smartphone (please complete the following information, if applicable):**

- Device: [e.g. Samsumg S20]
- OS: [e.g. Android]
- Version [e.g. 9 (Pie)]

**Package info:**

- Python version: 3.11.2
- Package version: 0.1.0 (note there is no `-V` arg)
- Installation method: `pipx`

**Terminal Emulator:**

- Name: Gnome Terminal, Kitty
- Version: 3.48.0, 0.26.5

**Additional context**

**Comment by AnonymouX47** [comment]
Thanks for the report.

Unfortunately, what I see in the screenshot couldn't have been produced by either of the terminal emulators mentioned.

Did you run `termvisage` within `tmux` or some other terminal multiplexer?

**Comment by kianmeng** [comment]
I've tried disabling `tmux`, as well as create another new user account with bash shell without `tmux` to test it out. Issue remains the same.

**Comment by AnonymouX47** [comment]
The shell shouldn't matter.

Please, try the following:

- Open a **new** Kitty Terminal window.
- Ensure you aren't working within `tmux` or any other terminal multiplexer.
- Run `termvisage ...`
- Run `echo $TERM_PROGRAM`
- Run `kitty +kitten query_terminal`
- Share a full screenshot of the terminal window.

**Comment by kianmeng** [comment]
Yup, it worked for me this time, after disabling `tmux` and use `kitty`, not `gnome-terminal`. Thanks.

```sh
$ echo $TERM_PROGRAM

$ kitty +kitten query_terminal
allow_hyperlinks: yes
bold_font: NotoSansMono-Bold
bold_italic_font: NotoSansMono-Bold
clipboard_control: write-clipboard write-primary read-clipboard-ask read-primary-ask
font_family: NotoSansMono-Regular
font_size: 11
italic_font: NotoSansMono-Regular
name: xterm-kitty
version: 0.26.5
```

![Screenshot from 2023-07-22 12-54-11](https://github.com/AnonymouX47/termvisage/assets/134518/4d7f24c4-0916-4614-af1b-0034486a8107)

**Comment by AnonymouX47** [comment]
Oh, great! You're welcome.

Also, I think it's worth noting the following:

- support for `tmux` passthrough is underway. This will allow high-resolution images within `tmux`, though with certain limitations.
- support a relatively new kitty graphics' **Virtual Placements** is underway, see https://github.com/AnonymouX47/term-image/issues/40#issuecomment-1510480395. This will allow for proper display of images within terminal multiplexers, though it's only limited to the Kitty Terminal so far.

These features will be implemented in the library, [term-image](https://github.com/AnonymouX47/term-image) first and then incorporated herein.

Thanks.

**Comment by AnonymouX47** [comment]
Oh, great! You're welcome.

Also, I think it's worth noting the following:

- support for `tmux` passthrough is underway. This will allow high-resolution images within `tmux`, though with certain limitations.
- support a relatively new kitty graphics' **Virtual Placements** is underway, see https://github.com/AnonymouX47/term-image/issues/40#issuecomment-1510480395. This will allow for proper display of images within terminal multiplexers, though it's only limited to the Kitty Terminal so far.

These features will be implemented in the library, [term-image](https://github.com/AnonymouX47/term-image) first and then incorporated herein.

Thanks.
